/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Model.DeveloperDetails;
import Model.Task;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
import java.util.HashMap;
import java.util.Map;

/**
 * @author ME
 */
public class AddTaskDetailsDialog extends javax.swing.JDialog {


    public static Map<Integer, Object> TASKS_DB = new HashMap();
    boolean isEdit;
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddTaskDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddTaskDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddTaskDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddTaskDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                AddTaskDetailsDialog dialog = new AddTaskDetailsDialog(new javax.swing.JFrame(), true, false);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField developerNameTextField;
    private javax.swing.JTextField developerSurnameTextField;
    private javax.swing.JLabel errorStatusjLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelWelcomeMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameOfTaskTextField;
    private javax.swing.JTextArea taskDescriptionTextArea;
    private javax.swing.JTextField taskDurationTextField;
    private javax.swing.JTextField taskIDTextField;
    private javax.swing.JTextField taskNumberjTextField;
    private javax.swing.JComboBox<String> taskStatusjComboBox;
    /**
     * Creates new form FeatureDialog
     */
    public AddTaskDetailsDialog(java.awt.Frame parent, boolean modal, boolean isEdit) {
        super(parent, modal);
        initComponents();
        this.isEdit = isEdit;
        errorStatusjLabel.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWelcomeMessage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameOfTaskTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        taskNumberjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        taskDurationTextField = new javax.swing.JTextField();
        taskIDTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taskDescriptionTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        developerNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        developerSurnameTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        taskStatusjComboBox = new javax.swing.JComboBox<>();
        errorStatusjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelWelcomeMessage.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        jLabelWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcomeMessage.setText("Welcome to EasyKanban");
        jLabelWelcomeMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setText("Enter Task Details");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Name of Task");

        nameOfTaskTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        nameOfTaskTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameOfTaskTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Description of Task");

        taskNumberjTextField.setEditable(false);
        taskNumberjTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel4.setText("Task Number");

        jLabel7.setText("Duration of Task");

        taskDurationTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        taskIDTextField.setEditable(false);
        taskIDTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel8.setText("Task ID");

        jLabel9.setText("Status of Task");

        taskDescriptionTextArea.setColumns(20);
        taskDescriptionTextArea.setLineWrap(true);
        taskDescriptionTextArea.setRows(5);
        taskDescriptionTextArea.setToolTipText("");
        taskDescriptionTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        taskDescriptionTextArea.setName("taskDescriptionTextArea"); // NOI18N
        jScrollPane1.setViewportView(taskDescriptionTextArea);

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Details of Developer Assigned the task");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        developerNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel5.setText("Developer Name");

        jLabel6.setText("Developer Surname");

        developerSurnameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(developerNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                        .addComponent(developerSurnameTextField))
                                .addContainerGap())
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel10)
                                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(developerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(developerSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Accept Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        taskStatusjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"To Do", "In Progress", "Done"}));
        taskStatusjComboBox.setBorder(null);

        errorStatusjLabel.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        errorStatusjLabel.setForeground(new java.awt.Color(242, 242, 242));
        errorStatusjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorStatusjLabel.setText("****");
        errorStatusjLabel.setToolTipText("Error Status");
        errorStatusjLabel.setFocusable(false);
        errorStatusjLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel9))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(taskNumberjTextField)
                                                        .addComponent(taskIDTextField)
                                                        .addComponent(taskDurationTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(nameOfTaskTextField)
                                                        .addComponent(taskStatusjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(87, 87, 87))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(259, 259, 259)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(296, 296, 296))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(errorStatusjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(nameOfTaskTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(taskNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(taskDurationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(taskIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(taskStatusjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(errorStatusjLabel)
                                .addGap(9, 9, 9)
                                .addComponent(jButton1)
                                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabelWelcomeMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelWelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameOfTaskTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameOfTaskTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameOfTaskTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addTaskValidation();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void addTaskValidation() {
        LineBorder border = new LineBorder(Color.red);

        if (isEdit) {
            errorStatusjLabel.setForeground(Color.green);
            errorStatusjLabel.setText("Edit Successful");
            JOptionPane.showMessageDialog(this, "Edit Successful");
            this.dispose();
            return;
        }

        if (nameOfTaskTextField.getText().isEmpty())
            nameOfTaskTextField.setBorder(border);
        if (taskDescriptionTextArea.getText().isEmpty())
            taskDescriptionTextArea.setBorder(border);
        if (developerNameTextField.getText().isEmpty())
            developerNameTextField.setBorder(border);
        if (developerSurnameTextField.getText().isEmpty())
            developerSurnameTextField.setBorder(border);
        if (taskDurationTextField.getText().isEmpty())
            taskDurationTextField.setBorder(border);

        try {
            Task task = new Task(
                    nameOfTaskTextField.getText(),
                    String.valueOf(TASKS_DB.size()),
                    taskDescriptionTextArea.getText(),
                    new DeveloperDetails(developerNameTextField.getText(),
                            developerSurnameTextField.getText()),
                    taskDurationTextField.getText(),
                    taskStatusjComboBox.getSelectedItem().toString());

            if (task.checkExistenceOfTask()) {
                errorStatusjLabel.setForeground(Color.red);
                errorStatusjLabel.setText(task.printTaskAdditionResult());
            } else if (!task.checkTaskDescription()) {
                errorStatusjLabel.setForeground(Color.red);
                errorStatusjLabel.setText(task.printTaskAdditionResult());
                throw new Exception("Please enter a task description of less"
                        + " than 50 characters");
            } else {
                nameOfTaskTextField.setBorder(new LineBorder(Color.WHITE));
                taskDescriptionTextArea.setBorder(new LineBorder(Color.WHITE));
                developerNameTextField.setBorder(new LineBorder(Color.WHITE));
                developerSurnameTextField.setBorder(new LineBorder(Color.WHITE));
                taskDurationTextField.setBorder(new LineBorder(Color.WHITE));

                errorStatusjLabel.setForeground(Color.green);
                errorStatusjLabel.setText(task.printTaskAdditionResult());
                JOptionPane.showMessageDialog(this, task.printTaskDetails());
                TASKS_DB.put(TASKS_DB.size(), task);
                this.dispose();
            }
        } catch (Exception exc) {
            errorStatusjLabel.setForeground(Color.red);
            errorStatusjLabel.setText(exc.getMessage());
        }
    }
    // End of variables declaration//GEN-END:variables

    public JTextField getDeveloperNameTextField() {
        return developerNameTextField;
    }

    public void setDeveloperNameTextField(JTextField developerNameTextField) {
        this.developerNameTextField = developerNameTextField;
    }

    public JTextField getDeveloperSurnameTextField() {
        return developerSurnameTextField;
    }

    public void setDeveloperSurnameTextField(JTextField developerSurnameTextField) {
        this.developerSurnameTextField = developerSurnameTextField;
    }

    public JTextField getNameOfTaskTextField() {
        return nameOfTaskTextField;
    }

    public void setNameOfTaskTextField(JTextField nameOfTaskTextField) {
        this.nameOfTaskTextField = nameOfTaskTextField;
    }

    public JTextArea getTaskDescriptionTextArea() {
        return taskDescriptionTextArea;
    }

    public void setTaskDescriptionTextArea(JTextArea taskDescriptionTextArea) {
        this.taskDescriptionTextArea = taskDescriptionTextArea;
    }

    public JTextField getTaskDurationTextField() {
        return taskDurationTextField;
    }

    public void setTaskDurationTextField(JTextField taskDurationTextField) {
        this.taskDurationTextField = taskDurationTextField;
    }

    public JTextField getTaskIDTextField() {
        return taskIDTextField;
    }

    public void setTaskIDTextField(JTextField taskIDTextField) {
        this.taskIDTextField = taskIDTextField;
    }

    public JTextField getTaskNumberjTextField() {
        return taskNumberjTextField;
    }

    public void setTaskNumberjTextField(JTextField taskNumberjTextField) {
        this.taskNumberjTextField = taskNumberjTextField;
    }

    public JComboBox<String> getTaskStatusjComboBox() {
        return taskStatusjComboBox;
    }

    public void setTaskStatusjComboBox(JComboBox<String> taskStatusjComboBox) {
        this.taskStatusjComboBox = taskStatusjComboBox;
    }
}
