/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.DeveloperDetails;
import Model.Task;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;

import static View.AddTaskDetailsDialog.TASKS_DB;

/**
 * @author ME
 */
public class KanbanBoard extends javax.swing.JFrame {

    DefaultListModel toDoModel = new DefaultListModel();
    DefaultListModel inProgressModel = new DefaultListModel();
    DefaultListModel doneModel = new DefaultListModel();
    AddTaskDetailsDialog dialog;
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KanbanBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KanbanBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KanbanBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KanbanBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KanbanBoard().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBackToTaskBoard;
    private javax.swing.JButton jButtonBackToTaskBoard1;
    private javax.swing.JComboBox<String> jComboBoxNumberOfTasks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelWelcomeMessage;
    private javax.swing.JList<String> jListDone;
    private javax.swing.JList<String> jListInProgress;
    private javax.swing.JList<String> jListTodo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldTotalNumberOfHours;
    /**
     * Creates new form KanbanBoard
     */
    public KanbanBoard() {
        initComponents();
        jComboBoxNumberOfTasks.setSelectedIndex(0);
        jTextFieldTotalNumberOfHours.setText(String.valueOf(Task.returnTotalHours()) + "hr(s)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWelcomeMessage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDone = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTodo = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListInProgress = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonBackToTaskBoard = new javax.swing.JButton();
        jButtonBackToTaskBoard1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxNumberOfTasks = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTotalNumberOfHours = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelWelcomeMessage.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        jLabelWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcomeMessage.setText("<html> Welcome to EasyKanban  <div align=\"center\"> <h4> Task Board </h4> </div> </html>");
        jLabelWelcomeMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jListDone.setName("doneList"); // NOI18N
        jListDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListDoneMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListDone);

        jListTodo.setName("todoList"); // NOI18N
        jListTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListTodoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListTodo);

        jListInProgress.setName("inProgressList"); // NOI18N
        jListInProgress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListInProgressMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListInProgress);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("To Do");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("In Progress");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Done");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[]{jScrollPane1, jScrollPane2, jScrollPane3});

        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(17, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[]{jScrollPane1, jScrollPane2, jScrollPane3});

        jButton2.setText("Show report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Add Tasks");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Quit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2)
                                        .addComponent(jButton3)
                                        .addComponent(jButton1))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonBackToTaskBoard.setText("Back");

        jButtonBackToTaskBoard1.setText("Logout");

        jLabel4.setText("Number of Tasks :");

        jComboBoxNumberOfTasks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "30", "40"}));

        jLabel5.setText("Total number of hours:");

        jTextFieldTotalNumberOfHours.setEditable(false);
        jTextFieldTotalNumberOfHours.setText("0hr(s)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBoxNumberOfTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldTotalNumberOfHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jButtonBackToTaskBoard)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelWelcomeMessage)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonBackToTaskBoard1))
                                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelWelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonBackToTaskBoard1)
                                        .addComponent(jButtonBackToTaskBoard))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jComboBoxNumberOfTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(jTextFieldTotalNumberOfHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaskReport().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateListViewModel(
            boolean isString,
            ActionEvent evt,
            DefaultListModel list,
            List<Object> tasksDone,
            JList<String> jList) {
        for (Object obj : tasksDone) {
            Task task = (Task) obj;
            if (isString) {
                if (list.contains((String) evt.getSource())) {
                    int index = list.indexOf((String) evt.getSource());
                    list.removeElement((String) evt.getSource());
                    Optional<Object> taskValue = AddTaskDetailsDialog.TASKS_DB.entrySet()
                            .stream()
                            .filter(e -> e.getKey() == index)
                            .map(Map.Entry::getValue).findFirst();
                    if (list.size() == 0)
                        list.addElement(evt.getActionCommand());
                    else
                        list.insertElementAt(evt.getActionCommand(), index);
                    break;
                }
            } else {
                if (!list.contains(task.getTaskName())) {
                    list.addElement(task.getTaskName());
                    break;
                }
            }
        }
        jList.setModel(list);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean isNumberOfTasksMore =
                TASKS_DB.size() >=
                        Integer.
                                parseInt(jComboBoxNumberOfTasks.getSelectedItem()
                                        .toString());

        if (isNumberOfTasksMore) {
            JOptionPane.showMessageDialog(rootPane,
                    "Cannot add more than defined number of tasks");
            return;
        }

        boolean isString;
        isString = evt.getSource() instanceof String;
        //it means instead of the task being new, it's actually edited
        if (evt.getID() != -2) {
            new AddTaskDetailsDialog(this, rootPaneCheckingEnabled, false).show();
            jTextFieldTotalNumberOfHours
                    .setText(String.valueOf(Task.returnTotalHours()) + "hr(s)");
        }

        List<Object> tasksToDo = AddTaskDetailsDialog.TASKS_DB.entrySet()
                .stream()
                .filter(e -> "To Do"
                        .equals(((Task) e.getValue()).getTaskStatus()))
                .map(Map.Entry::getValue).collect(Collectors.toList());
        List<Object> tasksInProgress = AddTaskDetailsDialog.TASKS_DB.entrySet()
                .stream()
                .filter(e -> "In Progress".equals(((Task) e.getValue()).getTaskStatus()))
                .map(Map.Entry::getValue).collect(Collectors.toList());
        List<Object> tasksDone = AddTaskDetailsDialog.TASKS_DB.entrySet()
                .stream()
                .filter(e -> "Done".equals(((Task) e.getValue()).getTaskStatus()))
                .map(Map.Entry::getValue).collect(Collectors.toList());


        updateListViewModel(isString, evt, toDoModel, tasksToDo, jListTodo);

        updateListViewModel(isString, evt, inProgressModel, tasksInProgress,
                jListInProgress);

        updateListViewModel(isString, evt, doneModel, tasksDone, jListDone);
        jTextFieldTotalNumberOfHours
                .setText(String.valueOf(Task.returnTotalHours()) + "hr(s)");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jListTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTodoMouseClicked
        modifyTaskEventMouseOnClick(evt);
    }//GEN-LAST:event_jListTodoMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void populateAddTaskDetailsWithExistingTask(Task task, String status) {

        dialog.getNameOfTaskTextField().setText(task.getTaskName());
        dialog.getTaskDescriptionTextArea().setText(task.getTaskDescription());
        dialog.getTaskNumberjTextField().setText(task.getTaskNumber());
        dialog.getDeveloperNameTextField().setText(
                task.getTaskDeveloperDetails().getDevFirstName());
        dialog.getDeveloperSurnameTextField().setText(
                task.getTaskDeveloperDetails().getDevLastName());
        dialog.getTaskDurationTextField().setText(
                task.getTaskDuration().toString());
        dialog.getTaskIDTextField().setText(task.getTaskID());
        dialog.getTaskStatusjComboBox().setSelectedItem(status);
    }

    private String statusFromTheBoard(JList<String> list) {
        return list.getName().toLowerCase()
                .contains("todo") ?
                "To Do" : list.getName().toLowerCase()
                .contains("inprogress") ? "In Progress" : "Done";
    }

    private Optional<Object> taskFromTheMapOfTasks(String status,
                                                   JList<String> list) {
        return AddTaskDetailsDialog
                .TASKS_DB.entrySet()
                .stream()
                .filter(e -> status
                        .equals(((Task) e.getValue()).getTaskStatus()) &&
                        list.getSelectedValue()
                                .equals(((Task) e.getValue()).getTaskName()))
                .map(Map.Entry::getValue).findFirst();
    }

    private Integer indexOfItemBeingRemoved(String status,
                                            String selectedValueOnList) {
        return AddTaskDetailsDialog
                .TASKS_DB.entrySet().stream().filter(e -> status
                        .equals(((Task) e.getValue()).getTaskStatus()) &&
                        selectedValueOnList
                                .equals(((Task) e.getValue()).getTaskName()))
                .map(Map.Entry::getKey).findFirst().get();
    }

    private void removeFromMapOfTasks(Task task) {
        AddTaskDetailsDialog.TASKS_DB.entrySet()
                .removeIf(e -> task.getTaskID()
                        .equals(((Task) e.getValue()).getTaskID()));
    }

    private void editExistingTask(Task task) {

        task.setTaskName(dialog.getNameOfTaskTextField().getText());
        task.setTaskDescription(dialog.getTaskDescriptionTextArea().getText());
        task.setTaskNumber(dialog.getTaskNumberjTextField().getText());
        task.setTaskDeveloperDetails(new DeveloperDetails
                (dialog.getDeveloperNameTextField().getText(),
                        dialog.getDeveloperSurnameTextField().getText()));
        task.setTaskDuration(Integer.parseInt
                (dialog.getTaskDurationTextField().getText()));
        task.setTaskID(dialog.getTaskIDTextField().getText());
        task.setTaskStatus(
                dialog.getTaskStatusjComboBox()
                        .getSelectedItem().toString());
    }

    private void moveEditedTaskToTheAppropriateBoard(Task task) {
        switch (dialog.getTaskStatusjComboBox().getSelectedItem().toString()) {
            case "To Do":
                toDoModel.addElement(task.getTaskName());
                jListTodo.setModel(toDoModel);
                break;
            case "Done":
                doneModel.addElement(task.getTaskName());
                jListDone.setModel(doneModel);
                break;
            case "In Progress":
                inProgressModel.addElement(task.getTaskName());
                jListInProgress.setModel(inProgressModel);
                break;
            default:
                break;
        }
    }

    private void modifyTaskEventMouseOnClick(MouseEvent evt) {
        //Get the JList source (To Do, In Progress, Done
        JList<String> list = ((JList<String>) evt.getSource());
        if (list.getSelectedValue() == null)
            return;

        String selectedValueOnList = list.getSelectedValue();

        if (evt.getClickCount() == 1) {
            int index = list.locationToIndex(evt.getPoint());
            if (index != -1) {
                dialog = new AddTaskDetailsDialog(this,
                        rootPaneCheckingEnabled, true);
                String status = statusFromTheBoard(list);

                //Get the list model
                DefaultListModel listModel = (DefaultListModel) list.getModel();
                //We want to search for that task in our database
                Optional<Object> taskFromDB = taskFromTheMapOfTasks(status,
                        list);

                //Once retrieved from the database populate the fields in
                //dialog with the database fetched from the database
                Task task = (Task) taskFromDB.get();
                populateAddTaskDetailsWithExistingTask(task, status);

                //Show the dialog with all the data populated
                dialog.show();
                //Do the same actions as adding a new item in the kanban list
                //except that this time don't open up a new and empty dialog box
                this.jButton1ActionPerformed(new ActionEvent(task.getTaskName(),
                        -2, dialog.getNameOfTaskTextField().getText()));

                if (!dialog.getTaskStatusjComboBox()
                        .getSelectedItem().equals(status)) {
                    int indexOfRemovedItem = indexOfItemBeingRemoved(status,
                            selectedValueOnList);
                    removeFromMapOfTasks(task);
                    editExistingTask(task);

                    //move from old list board, and update the list view
                    listModel.removeElement(task.getTaskName());
                    list.setModel(listModel);

                    moveEditedTaskToTheAppropriateBoard(task);

                    AddTaskDetailsDialog.TASKS_DB.put(indexOfRemovedItem, task);

                } else {
                    int indexOfRemovedItem = indexOfItemBeingRemoved(status,
                            selectedValueOnList);
                    removeFromMapOfTasks(task);
                    editExistingTask(task);

                    AddTaskDetailsDialog.TASKS_DB.put(indexOfRemovedItem, task);
                }
            }
        }
    }

    private void jListInProgressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListInProgressMouseClicked
        modifyTaskEventMouseOnClick(evt);
    }//GEN-LAST:event_jListInProgressMouseClicked

    private void jListDoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListDoneMouseClicked
        modifyTaskEventMouseOnClick(evt);
    }//GEN-LAST:event_jListDoneMouseClicked
    // End of variables declaration//GEN-END:variables
}
